/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Reespaldos;

import programas.*;
import clases.ArbolBinario;
import clases.Nodo;
import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Font;
import java.awt.FontMetrics;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;

/**
 *
 * @author diego123
 */
public class PanelDibujo2 extends javax.swing.JPanel {

    private ArbolBinario arbolito;

    /**
     * Creates new form PanelDibujo
     */
    public PanelDibujo2() {
        initComponents();
        this.arbolito = new ArbolBinario();
        this.setBackground(Color.WHITE);
    }

    public PanelDibujo2(ArbolBinario arbol) {
        initComponents();
        this.arbolito = arbol;
        this.setBackground(Color.WHITE);
    }

    public void setArbol(ArbolBinario arbol) {
        this.arbolito = arbol;
        repaint();
    }

    public ArbolBinario getArbol() {
        return arbolito;
    }

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        Graphics2D g2 = (Graphics2D) g;
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        dibujarArbol(g2);
    }

    private int calcularAncho(Nodo nodo) {
        if (nodo == null) {
            return 0;
        }
        int izq = calcularAncho(nodo.izq);
        int der = calcularAncho(nodo.der);
        return Math.max(1, izq + der);
    }

    private void dibujarNodoBalanceado(Graphics2D g, Nodo nodo, int x, int y) {
        if (nodo == null) {
            return;
        }

        int r = 15;
        int diam = r * 2;
        int espacioVertical = 65;

        int anchoIzq = calcularAncho(nodo.izq);
        int anchoDer = calcularAncho(nodo.der);

        int separacionBase = 35;
        int offsetIzq = anchoIzq * separacionBase;
        int offsetDer = anchoDer * separacionBase;

        g.setColor(Color.BLACK);
        g.setStroke(new BasicStroke(2));

        if (nodo.izq != null) {
            int xH = x - offsetIzq;
            int yH = y + espacioVertical;
            g.drawLine(x, y + r, xH, yH - r);
            dibujarNodoBalanceado(g, nodo.izq, xH, yH);
        }

        if (nodo.der != null) {
            int xH = x + offsetDer;
            int yH = y + espacioVertical;
            g.drawLine(x, y + r, xH, yH - r);
            dibujarNodoBalanceado(g, nodo.der, xH, yH);
        }

        g.setColor(Color.GREEN);
        g.fillOval(x - r, y - r, diam, diam);
        g.setColor(Color.BLACK);
        g.drawOval(x - r, y - r, diam, diam);

        g.setFont(new Font("Arial", Font.BOLD, 10));
        String txt = nodo.dato.toString();
        FontMetrics fm = g.getFontMetrics();
        int w = fm.stringWidth(txt);
        g.drawString(txt, x - w / 2, y + 4);
    }

    //dibuja el árbol con el método nuevo
    private void dibujarArbol(Graphics2D g) {
        g.setColor(Color.WHITE);
        g.fillRect(0, 0, getWidth(), getHeight());

        if (arbolito == null || arbolito.getRaiz() == null) {
            g.setColor(Color.RED);
            g.setFont(new Font("Arial", Font.BOLD, 16));
            String cad = "ARBOL VACIO";
            FontMetrics k = g.getFontMetrics();
            int ancho = k.stringWidth(cad);
            int x = (getWidth() - ancho) / 2;
            int y = getHeight() / 2;
            g.drawString(cad, x, y);
            return;
        }

        dibujarNodoBalanceado(g, arbolito.getRaiz(), getWidth() / 2, 50);

        g.setColor(Color.BLUE);
        g.setFont(new Font("Arial", Font.BOLD, 12));
        String datos = "ALTURA: " + arbolito.altura() + " | PESO: " + arbolito.peso();
        g.drawString(datos, 10, 20);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
