/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package programas;

import clases.ArbolBinario;
import clases.ModificacionesJframe;
import javax.swing.JOptionPane;
import clases.Busqueda;
/**
 *
 * @author diego123
 */
public class ArbolDibujo extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ArbolDibujo.class.getName());
    private ArbolBinario arbolito;
    private PanelDibujo panelarbolito;

    /**
     * Creates new form ArbolDibujo
     */
    public ArbolDibujo() {
        initComponents();
        arbolito = new ArbolBinario();
        
        panelarbolito = new PanelDibujo(arbolito);
        jPanel2.setVisible(false);
        jPanel1.add(panelarbolito);
        
        panelarbolito.setBounds(jPanel2.getBounds());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Insertar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        CampoInsertar = new javax.swing.JTextField();
        Eliminar = new javax.swing.JButton();
        CampoEliminar = new javax.swing.JTextField();
        MostrarRecorridos = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        preorden = new javax.swing.JButton();
        postorden = new javax.swing.JButton();
        Inorden = new javax.swing.JButton();
        CampoBuscar = new javax.swing.JTextField();
        Buscar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(215, 204, 200));

        Insertar.setBackground(new java.awt.Color(187, 222, 251));
        Insertar.setFont(new java.awt.Font("Georgia", 3, 14)); // NOI18N
        Insertar.setForeground(new java.awt.Color(0, 0, 0));
        Insertar.setText("Insertar");
        Insertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertarActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(204, 255, 204));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 4, true));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 879, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 481, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Arial", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setText("ARBOL BINARIO DE BUSQUEDA");

        CampoInsertar.setBackground(new java.awt.Color(255, 255, 255));
        CampoInsertar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 51, 153), 3, true));
        CampoInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoInsertarActionPerformed(evt);
            }
        });

        Eliminar.setBackground(new java.awt.Color(187, 222, 251));
        Eliminar.setFont(new java.awt.Font("Georgia", 3, 14)); // NOI18N
        Eliminar.setForeground(new java.awt.Color(0, 0, 0));
        Eliminar.setText("Eliminar");
        Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarActionPerformed(evt);
            }
        });

        CampoEliminar.setBackground(new java.awt.Color(255, 255, 255));
        CampoEliminar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 51, 153), 3, true));
        CampoEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoEliminarActionPerformed(evt);
            }
        });

        MostrarRecorridos.setBackground(new java.awt.Color(206, 147, 216));
        MostrarRecorridos.setFont(new java.awt.Font("Georgia", 3, 14)); // NOI18N
        MostrarRecorridos.setForeground(new java.awt.Color(0, 0, 0));
        MostrarRecorridos.setText("Mostrar");
        MostrarRecorridos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MostrarRecorridosActionPerformed(evt);
            }
        });

        jTextArea2.setEditable(false);
        jTextArea2.setBackground(new java.awt.Color(255, 255, 204));
        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Georgia", 3, 14)); // NOI18N
        jTextArea2.setForeground(new java.awt.Color(0, 0, 0));
        jTextArea2.setRows(5);
        jTextArea2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(55, 71, 79), 3, true));
        jScrollPane2.setViewportView(jTextArea2);

        preorden.setBackground(new java.awt.Color(225, 190, 231));
        preorden.setFont(new java.awt.Font("Georgia", 3, 14)); // NOI18N
        preorden.setForeground(new java.awt.Color(0, 0, 0));
        preorden.setText("Preorden");
        preorden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                preordenActionPerformed(evt);
            }
        });

        postorden.setBackground(new java.awt.Color(225, 190, 231));
        postorden.setFont(new java.awt.Font("Georgia", 3, 14)); // NOI18N
        postorden.setForeground(new java.awt.Color(0, 0, 0));
        postorden.setText("Postorden");
        postorden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                postordenActionPerformed(evt);
            }
        });

        Inorden.setBackground(new java.awt.Color(225, 190, 231));
        Inorden.setFont(new java.awt.Font("Georgia", 3, 14)); // NOI18N
        Inorden.setForeground(new java.awt.Color(0, 0, 0));
        Inorden.setText("Inorden");
        Inorden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InordenActionPerformed(evt);
            }
        });

        CampoBuscar.setBackground(new java.awt.Color(255, 255, 255));
        CampoBuscar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 51, 153), 3, true));
        CampoBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoBuscarActionPerformed(evt);
            }
        });

        Buscar.setBackground(new java.awt.Color(187, 222, 251));
        Buscar.setFont(new java.awt.Font("Georgia", 3, 14)); // NOI18N
        Buscar.setForeground(new java.awt.Color(0, 0, 0));
        Buscar.setText("Buscar");
        Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(450, 450, 450)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(MostrarRecorridos)
                        .addGap(202, 202, 202)
                        .addComponent(CampoInsertar, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Insertar)
                        .addGap(18, 18, 18)
                        .addComponent(CampoEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Eliminar)
                        .addGap(18, 18, 18)
                        .addComponent(CampoBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(preorden)
                                .addGap(43, 43, 43)
                                .addComponent(postorden))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(98, 98, 98)
                                .addComponent(Inorden)))
                        .addGap(42, 42, 42)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(107, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Insertar)
                    .addComponent(CampoInsertar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Eliminar)
                    .addComponent(CampoEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MostrarRecorridos)
                    .addComponent(CampoBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Buscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(preorden)
                            .addComponent(postorden))
                        .addGap(18, 18, 18)
                        .addComponent(Inorden)))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void InsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertarActionPerformed
        String d = CampoInsertar.getText().trim().toUpperCase();
        try {
                if (d.isEmpty()) throw new Exception("El campo esta vacio");
                if (d.length() != 1 || !Character.isLetter(d.charAt(0))) 
                    throw new Exception ("Solo se permite una letra (Nada de numeros)");

                arbolito.insertar(d.charAt(0));
                panelarbolito.repaint();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "ERROR AL INSERTAR: " + e.getMessage(),
                        "ERROR", JOptionPane.ERROR_MESSAGE);
            }
        CampoInsertar.setText("");
    }//GEN-LAST:event_InsertarActionPerformed

    private void CampoInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoInsertarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoInsertarActionPerformed

    private void CampoEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoEliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoEliminarActionPerformed

    private void MostrarRecorridosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MostrarRecorridosActionPerformed
        String opcion = (String) JOptionPane.showInputDialog(null, "¿QUE RECORRIDO DESEA HACER?", "RECORRIDOS", JOptionPane.INFORMATION_MESSAGE,
                null, new Object[]{"PREORDEN", "POSTORDEN", "INORDEN", "TODOS"}, null);

        if (opcion == null) return;
        
        ModificacionesJframe mode = new ModificacionesJframe(arbolito); //Tengo otra clase que involucra a este objeto
        switch (opcion) {
            case "PREORDEN":
                jTextArea2.setText(mode.obtenerPreorden());
                break;
            case "POSTORDEN":
                jTextArea2.setText(mode.obtenerPostorden());
                break;
            case "INORDEN":
                jTextArea2.setText(mode.obtenerInorden());
                break;
            case "TODOS":
                jTextArea2.setText(mode.obtenerPreorden() + "\n" + mode.obtenerPostorden() + "\n" + mode.obtenerInorden());
                break;
        }
    }//GEN-LAST:event_MostrarRecorridosActionPerformed

    private void EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarActionPerformed
        String d = CampoEliminar.getText().trim().toUpperCase();
            try {
                if (d.isEmpty()) throw new Exception("El campo esta vacio");
                if (d.length() != 1 || !Character.isLetter(d.charAt(0))) 
                    throw new Exception ("Ingrese solo 1 caracter y ademas que no sea de tipo numerico");

                arbolito.eliminar(d.charAt(0));
                panelarbolito.repaint();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "ERROR AL ELIMINAR: " + e.getMessage(),
                        "ERROR", JOptionPane.ERROR_MESSAGE);
            }
        CampoEliminar.setText("");
    }//GEN-LAST:event_EliminarActionPerformed

    private void InordenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InordenActionPerformed
        ModificacionesJframe mode = new ModificacionesJframe(arbolito);
        jTextArea2.setText(mode.obtenerInorden());
    }//GEN-LAST:event_InordenActionPerformed

    private void preordenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_preordenActionPerformed
        ModificacionesJframe mode = new ModificacionesJframe(arbolito);
        jTextArea2.setText(mode.obtenerPreorden());
    }//GEN-LAST:event_preordenActionPerformed

    private void postordenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_postordenActionPerformed
        ModificacionesJframe mode = new ModificacionesJframe(arbolito);
        jTextArea2.setText(mode.obtenerPostorden());
    }//GEN-LAST:event_postordenActionPerformed

    private void CampoBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoBuscarActionPerformed

    private void BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarActionPerformed
        Busqueda seguir;
        String d = CampoBuscar.getText().trim().toUpperCase();
        try{
            if (d.isEmpty()) throw new Exception("El campo esta vacio");
            if (d.length() != 1 || !Character.isLetter(d.charAt(0)))
                throw new Exception("Ingrese un solo caracter y ademas que no sea de tipo numerico");
            seguir = arbolito.BuscarNodo(d.charAt(0));
            jTextArea2.setText("RUTA ENCONTRADA:\n" + seguir.ruta + "\nEL CARACTER QUE BUSCA"
                    + "\nSE ENCUENTRA "
                    + "\nEN EL NIVEL: " + seguir.nivel);
            panelarbolito.resaltarRuta(seguir.ruta);
            /*jTextArea2.setText("RUTA ENCONTRADA:\n" + arbolito.BuscarNodo(d.charAt(0)));
            *panelarbolito.resaltarRuta(arbolito.BuscarNodo(d.charAt(0)));
            Si ocupo lo que esta comentado, en vez de optimizar pues se hara lento, ya que en vez
            de consultar una vez va hacer 2 recorridos de ruta entonces nope. */
            
            /*Actualizacion!!!
            Implemente un metodo para ambos llamado BuscarNodo pero ahora con nivel.
            */
            
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, "ERROR AL BUSCAR: " + e.getMessage(),
                        "ERROR", JOptionPane.ERROR_MESSAGE);
            panelarbolito.limpiar();
        }
        CampoBuscar.setText("");
    }//GEN-LAST:event_BuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ArbolDibujo().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Buscar;
    private javax.swing.JTextField CampoBuscar;
    private javax.swing.JTextField CampoEliminar;
    private javax.swing.JTextField CampoInsertar;
    private javax.swing.JButton Eliminar;
    private javax.swing.JButton Inorden;
    private javax.swing.JButton Insertar;
    private javax.swing.JButton MostrarRecorridos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JButton postorden;
    private javax.swing.JButton preorden;
    // End of variables declaration//GEN-END:variables
}
